# Site settings
title: Home
email: zhouyaoji@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the portfolio page for Joseph Catera. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zhouyaoji.com" # the base hostname & protocol for your site
twitter_username: zhouyaoji
github_username:  zhouyaoji

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

gems:
  - jekyll-sitemap

