# Site settings
title: Home
email: zhouyaoji@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the portfolio page for Joseph Catera. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zhouyaoji.com" # the base hostname & protocol for your site
twitter_username: zhouyaoji
github_username:  zhouyaoji

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments
permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

gems:
  - jekyll-sitemap

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

url: https://zhouyaoji.github.io


footer-links:
  dribbble:
  email: zhouyaoji@yahoo.com
  facebook: 
  flickr: zhouyaoji
  github: zhouyaoji 
  instagram: 
  linkedin: MetaAshley
  pinterest:
  rss: 
  twitter: zhouyaoji
  stackoverflow: zhouyaoji
  youtube: zhouyaoji
  googleplus: zhouyaoji
